name: Check & build packages

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - run: |
          npm install
          npm run build

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./${{ inputs.folder }}/package.json
          token: ${{ secrets.NPM_TOKEN }}
