name: Check & build packages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            folder:
              - './**'
      - uses: actions/setup-node@v2
        if: steps.changes.outputs.folder == 'true'
        with:
          node-version: '18'

      - shell: bash 
        if: steps.changes.outputs.folder == 'true'
        run: |
          npm install

      - uses: JS-DevTools/npm-publish@v1
        if: steps.changes.outputs.folder == 'true'
        with:
          token: ${{ secrets.NPM_TOKEN }}
